language: java
jdk: oraclejdk8

before_deploy:
- mvn -B package
- mkdir -p deploy/webapps
- mv target/*.war deploy/webapps/ROOT.war
- rm -rf target

deploy:
  provider: azure_web_apps
  username: radarapi
  site: aqrradarapi
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    secure: pM5iRTeD61kyiS+/JbGNgtu2v1sBYMYfYNVmO36lgfo0OD/OGN4aCbLwJWNGS1/Mgr6MlYzEYCWlDluyP7FcjyLuNwAjro0Xze7ECjMNT03aqSXI5oliYEFQaVdx9ghDfVqDfCL/sG95npChJtXZXxmHI3+KvC6HEv4PqgeN+urCL3JCT+9FeMkW6LLzUGVgzpttJ+6dkKKYMuQ4McKmV/kZI3qe+jR2ZeiVcHaj0ZpYTs68PC//cCM9EwHGJyf7bmN1DyCsCdL0Yckw7bkjgZX20ezrgkJS5WEGdZ2kFpYyVizoRiotj7nhTnAbUqI9qH34wWID2COK69B7X+Q1FJA2C4iVdoIs41RVl6Cd79XZ1HDxZ56kHVyI+daV3Tss65GEyGHnJLBsM4VP5CWdp3Ido98maMawwEp/8SCv7PzfOFbAs36XXp7YVW+W1b145XwLx5KTG6j3wa5gI8ZIHpPIE/TyEVuYNmLdpxGdp+an9isoGgsSxULLrORVbfC6KDqfYzm9lptWhPL0f6TYophRL3g7SVd6ZQzqzP1AD3+AeUwmtJgn0LMi4aQf0BD6Fi8wbSwEl4FgeJHJNuIgXSCsbBvNxnj46MoGw1KV9RxmztYdM++k07mFqXgN6iV8oESrEWnQfZSwPQaW2Lk86xj/O7r4Aa/Ox+PltNYvWJ4=

before_install:
- openssl aes-256-cbc -K $encrypted_6f6ead80179f_key -iv $encrypted_6f6ead80179f_iv
  -d -in src/main/java/uk/ac/cam/alpha2017/airqualityradar/backend/data/credentials/StorageCredentials.java.enc
  -out src/main/java/uk/ac/cam/alpha2017/airqualityradar/backend/data/credentials/StorageCredentials.java

env:
  global:
    secure: gCBnfQf0sDKTrvAlhyCG715LYa6w9SFMEPWWpN4Otnhwd7weg2cfTwQ/6PKFKAU79prWAuFljMU/i2jdOumvnG20YPl5g0TmOyorcnYQDQSzpjGZkPNitkCO2wV6Mj/WwQElr4kobVAGr9slXCBX5HLtDKnPdrGAS/KnTNKUfm/1el9rmVCsqCJ941+zBB0zie/E8JYzqdKj1XFHcP0Okq0zumGGH1lKEiz6lyTGGRQfIotFvFm1dSloeS1EJE5TW376qbHDkcJJu4zMsBJn0cyKyFoc1XxShgJO21R8jdHiZzk90RFEpQ35oGoKMwM17HscrGrPHgZDbc68rA1y6YJbFKgdEiNU2LxTPYSJCecsIsP+O9Q3cBU/pwkj04vnZ2lUk/9dC+OJnt4wIAC4oFBqOAaGc7kWBlSdxk3w+xVFKP6kvO9KZ1dJe4E1uLJ9SkEv6IrFzmjFMpo8gHFMrbCoCxVSJ2CQDhOsLRuNol07plaj9oDxz2xsO/MVr59Q/VR9ViPqziSiFWzhtXhDfsTbl8EoQeTcf7rZNzhW2QUiNHwJCe4OAFdeRgfF+CVCOrLM56w8T5XgDspCdR7ZOJql8waQbj4L7MEibwmHVRQOSJ/nkQ0SUTSy/8aCzwyt4K900XfT71n/Bg+22ffSzvKMk1HnCRZhFDg9F3sd5B8=
